POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "employee@worklog.com",
  "password": "Password123!",
  "firstName": "John",
  "lastName": "Doe"
}


//error beter afvangen in login
// uren invoerveld verbeteren
// uren nog laten zien bij taak details
// uren fixen
// achtergrond beetje lichtblauw met logo?
// misschien nog mooie grafiekjes in de dashboard
// admin mag geen taken hebben
// zoek functie op naam van project